[package]
name = "reactor-cache"
version = "0.1.0"
authors = ["Max Seiden <max@sigmacomputing.io>"]

[dependencies]
futures = "0.1.6"
linked-hash-map = "0.3.0"
log = "0.3"
mio = "0.6"
tokio-core = "0.1"
